name: Auto Repository Updates

on:
  schedule:
    - cron: '0 0 * * *'  # Daily at midnight

jobs:
  update-deps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Update dependencies
        run: |
          pip install pip-outdated
          pip-outdated
          
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: '⬆️ Update dependencies'
          title: '⬆️ Update dependencies'
          body: 'Automated dependency updates'
          branch: update-dependencies
          base: main