name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Generate reports
        run: |
          python scripts/generate_predictions_report.py
          python scripts/generate_monitoring_report.py
          python scripts/update_web_data.py
      
      - name: Setup Pages
        uses: actions/configure-pages@v3
      
      - name: Build site
        run: |
          mkdir -p ./dist
          cp -r web/* ./dist/
          cp -r reports ./dist/
      
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          force_orphan: true