name: Model Performance Monitoring

on:
  schedule:
    - cron: '*/30 * * * *'  # Run every 30 minutes
  workflow_dispatch:      # Manual trigger

jobs:
  monitor:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Download latest models
        uses: actions/download-artifact@v3
        with:
          name: ml-models
          path: models/
      
      - name: Run monitoring checks
        run: python scripts/run_monitoring.py
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      
      - name: Save metrics
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add metrics/
          git commit -m "📊 Update model metrics"
          git push
      
      - name: Generate monitoring report
        run: python scripts/generate_monitoring_report.py
      
      - name: Upload monitoring artifacts
        uses: actions/upload-artifact@v3
        with:
          name: monitoring-report
          path: reports/monitoring/