name: Market Alert Notifications

on:
  schedule:
    - cron: '*/15 * * * *'  # Check every 15 minutes

jobs:
  check-alerts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: pip install requests telegram-send discord.py
          
      - name: Check price alerts
        run: python scripts/check_alerts.py
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          
      - name: Send notifications
        if: success()
        run: python scripts/send_notifications.py
        env:
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          DISCORD_CHANNEL: ${{ secrets.DISCORD_CHANNEL }}